spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: broker:29092
      function.definition: receiveReport
      bindings:
        receiveReport-in-0:
          binder: kafka
          destination: report-topic
          group: report-service
