spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      function:
        definition: paymentProducer;logActivityPublisher
      bindings:
        paymentProducer-out-0:
          binder: kafka
          destination: payment-topic
        logActivityPublisher-out-0:
          binder: kafka
          destination: log-topic