server:port: 8180
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      function:
        definition: paymentProducer;logActivityPublisher;reportProducer
      bindings:
        paymentProducer-out-0:
          binder: kafka
          destination: payment-topic
        logActivityPublisher-out-0:
          binder: kafka
          destination: log-topic
        reportProducer-out-0:
          binder: kafka
          destination: report-topic