
server:
  port: 8182
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      function:
        definition: receiveLogActivity
      bindings:
        receiveLogActivity-in-0:
          destination: log-topic