server.port: 8181
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      function.definition: receivePayment
      bindings:
        receivePayment-in-0:
          binder: kafka
          destination: payment-topic
          group: email-service
